### ISSUE TITLE
Hi Dlzou, it's one wonderful project, do you have some new progress? thanks.

### ISSUE THREAD

**Issue by xinghui-sun** [dlzou/jianpu-omr#1]
@dlzou @FelixAou 
Hi Dlzou and FelixAou,
it's one wonderful project, do you have some new progress?
thanks.

**Comment by dlzou** [comment]
@xinghui-sun Thanks for your interest! Unfortunately, I haven't worked on this for some time due to school work and other projects more aligned with my current goals, and I don't foresee getting back to it in the near future.

In its current form the program can somewhat accurately segment symbols on a music sheet and categorize them based on location. Feel free to fork and add on :)

**Comment by xinghui-sun** [comment]
@dlzou  Thank you very much.
